acts2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mainapp import views

urlpatterns = [
    path('', include('mainapp.urls')),
    path('admin/', admin.site.urls),
] 

handler404 = views.error404

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('blogs/', views.listBlogContent, name='blog_list'),
    path('blog/<int:blog_id>/detail/', views.blogDetail, name='blog_detail'),
    path('comment/<int:blog_id>/', views.comment, name='comment'),
    path('contact/', views.contact, name='contact'),
    path('mail/', views.mail, name='send_mail'),
]

mainapp/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User

# Create your models here.
class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    url = models.CharField(max_length=1000)
    pub_date = models.DateTimeField('Date Published')
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    content = RichTextField()

    def __str__(self):
        return self.title

class Event(models.Model):
    description = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    date = models.DateTimeField('Event Date')
    url = models.CharField(max_length=1000, default='http://localhost:8000/static/mainapp/img/bg-img/10.jpg')

    def __str__(self):
        return self.description

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    author = models.CharField(max_length=30)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

mainapp/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.http import HttpResponseRedirect
from django.core.mail import send_mail
from django.contrib import messages
from django.core.paginator import Paginator
from django.urls import reverse
from django.core.files import File

from .models import Blog, Event, Comment

def index(request):
    
    events = get_list_or_404(Event)
    blogs = get_list_or_404(Blog)[:3]
    return render(request, 'mainapp/index.html', {
        'events': events,
        'blogs': blogs,
    })

def about(request):
    return render(request, 'mainapp/about.html')

def contact(request):
    return render(request, 'mainapp/contact.html')

def comment(request, blog_id):
    name = request.POST['name']
    content = request.POST['comment']
    blog = Blog.objects.get(pk=int(blog_id))
    comment = Comment.objects.create(blog=blog, author=name, content=content)
    return HttpResponseRedirect(reverse('mainapp:blog_detail', args=(blog_id,)))
    

def listBlogContent(request):
    blogs = get_list_or_404(Blog)
    paginator = Paginator(blogs, 4)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'mainapp/bloglist.html', {'page_obj': page_obj})

def blogDetail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'mainapp/blogdetail.html', {'blog': blog})

def mail(request):
    name = request.POST['name']
    email = request.POST['email']
    message = request.POST['message'] + ' sent by:' + email
    try:
        send_mail(('message from %s' % name),message, email, ['info.actschapter2@gmail.com'])
        messages.add_message(request, messages.SUCCESS, 'Mail sent successfully')
    except:
        messages.add_message(request, messages.WARNING, 'Mail not sent')
    return HttpResponseRedirect(reverse('mainapp:contact'),)

def error404(request, exception):
    return render(request, '404.html',{'exception': exception}, content_type='text/html', charset='utf-8', status=404, )

mainapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title -->
    <title>Acts 2 Ministries</title>

    <!-- Favicon -->
    <link rel="icon" href="{% static 'mainapp/img/core-img/favicon.ico' %}">

    <!-- Core Stylesheet -->
    <link rel="stylesheet" href="{% static 'mainapp/style.css' %}">

</head>

<body>
    <div class="preloader d-flex align-items-center justify-content-center">
        <!-- Line -->
        <div class="line-preloader"></div>
    </div>

    <!-- ##### Header Area Start ##### -->
    <header class="header-area">

        <!-- ***** Top Header Area ***** -->
        <div class="top-header">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="top-header-content d-flex flex-wrap align-items-center justify-content-between">
                            <!-- Top Header Meta -->
                            <div class="top-header-meta d-flex flex-wrap">
                                <!-- Social Info -->
                                <div class="top-social-info">
                                    <a target="_blank"
                                        href="https://www.facebook.com/Acts-Chapter-2-Ministries-763697534020654"><i
                                            class="fa fa-facebook" aria-hidden="true"></i></a>
                                    <a target="_blank" href="https://twitter.com/ActsChapter?s=08"><i
                                            class="fa fa-twitter" aria-hidden="true"></i></a>
                                    <a target="_blank" href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                                </div>
                            </div>
                            <!-- Top Header Meta -->
                            <div class="top-header-meta">
                                <span class="email-address"><i class="fa fa-envelope" aria-hidden="true"></i>
                                    <span>info.actschapter2@gmail.com</span></a>
                                </span>
                                <span class="phone"><i class="fa fa-phone" aria-hidden="true"></i> <span>+233 24 448
                                        2798
                                    </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- ***** Top Header Area ***** -->

        <!-- ***** Navbar Area ***** -->
        <div class="crose-main-menu">
            <div class="classy-nav-container breakpoint-off">
                <div class="container">
                    <!-- Menu -->
                    <nav class="classy-navbar justify-content-between" id="croseNav">

                        <!-- Nav brand -->
                        <a href="{% url 'mainapp:index' %}" class="nav-brand"><img
                                src="{% static 'mainapp/img/core-img/logo.png' %}" alt=""></a>

                        <!-- Navbar Toggler -->
                        <div class="classy-navbar-toggler">
                            <span class="navbarToggler"><span></span><span></span><span></span></span>
                        </div>

                        <!-- Menu -->
                        <div class="classy-menu">

                            <!-- close btn -->
                            <div class="classycloseIcon">
                                <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                            </div>

                            <!-- Nav Start -->
                            <div class="classynav">
                                <ul>
                                    <li><a href="{% url 'mainapp:index' %}">Home</a></li>
                                    <li><a href="{% url 'mainapp:blog_list' %}">Blog</a></li>
                                    <li><a href="{% url 'mainapp:about' %}">About</a></li>
                                    <li><a href="{% url 'mainapp:contact' %}">Contact</a></li>
                                    <li><a target="_blank" href="https://acts2chat.herokuapp.com">Prayer</a></li>
                                </ul>

                                <!-- Donate Button -->
                                <a href="#" class="btn crose-btn header-btn"
                                    onclick="alert('Please check back later')">Donate</a>

                            </div>
                            <!-- Nav End -->
                        </div>
                    </nav>
                </div>
            </div>

            <!-- ***** Search Form Area ***** -->
            <div class="search-form-area">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-12">
                            <div class="searchForm">
                                <form action="#" method="post">
                                    <input type="search" name="search" id="search"
                                        placeholder="Enter keywords &amp; hit enter...">
                                    <button type="submit" class="d-none"></button>
                                </form>
                                <div class="close-icon" id="searchCloseIcon"><i class="fa fa-close"
                                        aria-hidden="true"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- ***** Navbar Area ***** -->
    </header>

    {% block body %}

    {% endblock %}
    <!-- ##### Footer Area Start ##### -->
    <footer class="footer-area">
        <!-- Main Footer Area -->
        <div class="main-footer-area">
            <div class="container">
                <div class="row">

                    <!-- Single Footer Widget -->
                    <div class="col-12 col-sm-6 col-lg-3">
                        <div class="single-footer-widget mb-70">
                            <h5 class="widget-title">Social Links</h5>
                            <nav class="footer-menu">
                                <ul>
                                    <li><a target="_blank"
                                            href="https://www.facebook.com/Acts-Chapter-2-Ministries-763697534020654"><i
                                                class="fa fa-facebook" aria-hidden="true"></i> Facebook</a></li>
                                    <li><a target="_blank" href="https://twitter.com/ActsChapter?s=08"><i
                                                class="fa fa-twitter" aria-hidden="true"></i> Twitter</a></li>
                                    <li><a target="_blank" href="#"><i class="fa fa-instagram"
                                                aria-hidden="true"></i> Instagram</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>

                    <!-- Single Footer Widget -->
                    <div class="col-12 col-sm-6 col-lg-3">
                        <div class="single-footer-widget mb-70">
                            <h5 class="widget-title">Quick Link</h5>
                            <nav class="footer-menu">
                                <ul>
                                    <li><a href="{% url 'mainapp:index' %}"><i class="fa fa-angle-double-right"
                                                aria-hidden="true"></i> Home</a></li>
                                    <li><a href="{% url 'mainapp:blog_list' %}"><i class="fa fa-angle-double-right"
                                                aria-hidden="true"></i> Blog</a></li>
                                    <li><a href="{% url 'mainapp:about' %}"><i class="fa fa-angle-double-right"
                                                aria-hidden="true"></i> About Us</a></li>
                                    <li><a href="{% url 'mainapp:contact' %}"><i class="fa fa-angle-double-right"
                                                aria-hidden="true"></i> Contact</a></li>
                                    <li><a href="https://acts2chat.herokuapp.com"><i class="fa fa-angle-double-right"
                                                aria-hidden="true"></i> Prayer</a></li>
                                    <li><a href="#"><i class="fa fa-angle-double-right" aria-hidden="true"
                                                onclick="alert('Please check back later')"></i> Donate</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>


                    <!-- Single Footer Widget -->
                    <div class="col-12 col-sm-6 col-lg-3">
                        <div class="single-footer-widget mb-70">
                            <h5 class="widget-title">Contact Us</h5>

                            <div class="contact-information">
                                <p><i class="fa fa-map-marker" aria-hidden="true"></i> Achimota - Accra, Ghana
                                </p>
                                <a href="callto:+233244482798"><i class="fa fa-phone" aria-hidden="true"></i>
                                    +233 24 448 2798</a>
                                <a href="mailto:info.actschapter2@gmail.com"><i class="fa fa-envelope"
                                        aria-hidden="true"></i> info.actschapter2@gmail.com</a>
                            </div>

                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="copywrite-area">
            <div class="container h-100">
                <div class="row h-100 align-items-center flex-wrap">
                    <!-- Footer Social Icon -->
                    <div class="col-12 col-md-6">
                        <div class="footer-social-icon">
                            <a target="_blank"
                                href="https://www.facebook.com/Acts-Chapter-2-Ministries-763697534020654"><i
                                    class="fa fa-facebook" aria-hidden="true"></i></a>
                            <a target="_blank" href="https://twitter.com/ActsChapter?s=08"><i class="fa fa-twitter"
                                    aria-hidden="true"></i></a>
                            <a target="_blank" href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- ##### Footer Area End ##### -->
    <!-- jQuery-2.2.4 js -->
    <script src="{% static 'mainapp/js/jquery/jquery-2.2.4.min.js' %}"></script>
    <!-- Popper js -->
    <script src="{% static 'mainapp/js/bootstrap/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'mainapp/js/bootstrap/bootstrap.min.js' %}"></script>
    <!-- All Plugins js -->
    <script src="{% static 'mainapp/js/plugins/plugins.js' %}"></script>
    <!-- Active js -->
    <script src="{% static 'mainapp/js/active.js' %}"></script>
</body>

</html>

mainapp/templates/mainapp/blogdetail.html
{% extends '../base.html' %}
{% load static %}

{% block body %}
<!-- ##### Breadcrumb Area Start ##### -->
<div class="breadcrumb-area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Home</a></li>
                        <li class="breadcrumb-item"><a href="#">Blog</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Blog Details</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- ##### Breadcrumb Area End ##### -->

<!-- ##### Blog Content Area Start ##### -->
<section class="blog-content-area section-padding-100">
    <div class="container" style="width: 80% !important;">
        <div class="row justify-content-center">
            <!-- Blog Posts Area -->
            {% if blog %}
                <div class="col-24 col-lg-24">
                    <div class="blog-posts-area">

                        <!-- Post Details Area -->
                        <div class="single-post-details-area">
                            <div class="post-thumbnail mb-30">
                                <img src="{{ blog.url }}" alt="">
                            </div>
                            <div class="post-content">
                                <h4>{{ blog.title }}</h4>
                                {% autoescape off %}
                                {{ blog.content }}
                                {% endautoescape %}
                            </div>
                            <span>Published by {{ blog.author.username }} on {{ blog.pub_date }}</span>
                        </div>

                        <!-- Comment Area Start -->
                        <hr style="border: 1px solid grey; width: 80px; margin-bottom: 100px;">
                        <div>
                            <h4 class="headline">{% if blog.comment_set.all.count < 2 %}{{ blog.comment_set.all.count }} comment {% else %}{{ blog.comment_set.all.count }} comments {% endif %}</h4>
                            <hr style="border: 1px solid grey; width: 80px; margin-bottom: 50px;">
                            <ol>
                                <li class="single_comment_area">
                                    <div class="comment-wrapper">
                                        <!-- Comment Content -->
                                        {% for comment in blog.comment_set.all %}
                                        <div class="comment-content">
                                            <span class="comment-date">{{ comment.date }}</span>
                                            <h5>{{ comment.author }}</h5>
                                            <p>{{ comment.content }}
                                            </p>
                                        </div>
                                        {% endfor %}
                                    </div>
                                </li>
                            </ol>
                        </div>

                        <!-- Leave A Comment -->
                        <div class="leave-comment-area mt-50 clearfix">
                            <div class="comment-form">
                                <h4 class="headline">Leave A Comment</h4>
                                <!-- Contact Form Area -->
                                <div class="contact-form-area">
                                    <form action="{% url 'mainapp:comment' blog.id %}" method="post">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <input type="text" class="form-control" id="contact-name" name="name"
                                                        placeholder="Name">
                                                </div>
                                            </div>

                                            <div class="col-12">
                                                <div class="form-group">
                                                    <textarea class="form-control" name="comment" id="message" cols="30"
                                                        rows="10" placeholder="Comment"></textarea>
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <button type="submit" class="btn crose-btn mt-15">Post Comment</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            {% else %}
                <p>Nothing to show</p>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}

mainapp/templates/mainapp/bloglist.html
{% extends '../base.html' %}
{% load static %}

{% block body %}


<!-- ##### Breadcrumb Area Start ##### -->
<div class="breadcrumb-area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'mainapp:index' %}">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Blog</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- ##### Breadcrumb Area End ##### -->

<!-- ##### Blog Area Start ##### -->
<div class="blog-area section-padding-100">
    <div class="container" style="width: 80% !important;">
        <div class="row justify-content-between">
            <!-- Blog Post Area -->
            <div class="col-24 col-lg-20">
                <div class="row">

                    <!-- Single Blog Post Area -->
                    {% if page_obj %}
                    {% for blog in page_obj %}
                    <div class="col-12 col-md-6">
                        <div class="single-blog-post mb-50">
                            <div class="post-thumbnail">
                                <a href="{% url 'mainapp:blog_detail' blog.id %}"><img src="{% static 'mainapp/img/bg-img/10.jpg' %}" alt=""></a>
                            </div>
                            <div class="post-content">
                                <a href="{% url 'mainapp:blog_detail' blog.id %}" class="post-title">
                                    <h4>{{ blog.title }}</h4>
                                </a>
                                <div class="post-meta d-flex">
                                    <a href="#"><i class="fa fa-user" aria-hidden="true"></i> {{ blog.author.username }}</a>
                                    <a href="#"><i class="fa fa-calendar" aria-hidden="true"></i> {{ blog.pub_date }}</a>
                                </div>
                                <p class="post-excerpt">{{ blog.description }}</p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    {% else %}
                        <p>No blogs</p>
                    {% endif %}

                </div>
                <div class="pagination-area">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                            <li class="page-item active"><a class="page-link" href="?page=1" style="width: 80px;">first</a></li>
                            <li class="page-item active"><a class="page-link" href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-angle-left"></i></a></li>
                            {% endif %}
                            <li class="page-item" style="margin: 10px 0 0 30px;">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</li>
                            {% if page_obj.has_next %}
                            <li class="page-item active"><a class="page-link" href="?page={{ page_obj.next_page_number }}"><i class="fa fa-angle-right"></i></a></li>
                            <li class="page-item active"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" style="width: 80px;">last</a></li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>

            <!-- Sidebar Area -->
            
        </div>
    </div>
</div>
<!-- ##### Blog Area End ##### -->

{% endblock %}

mainapp/templates/mainapp/contact.html
{% extends '../base.html' %}
{% load static %}

{% block body %}
<!-- ##### Breadcrumb Area Start ##### -->
<div class="breadcrumb-area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'mainapp:index' %}"><i class="fa fa-home"></i>
                                Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Contact</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- ##### Breadcrumb Area End ##### -->
{% if messages %}
<ul class="messages" >
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
    </li>
        {% endfor %}
</ul>
{% endif %}
<!-- ##### Google Maps Start ##### -->
<div class="map-area" style="margin-top: 150px;">
    <!-- <iframe
        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d22236.40558254599!2d-118.25292394686001!3d34.057682914027104!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c2c75ddc27da13%3A0xe22fdf6f254608f4!2z4Kay4Ka4IOCmj-CmnuCnjeCmnOCnh-CmsuCnh-CmuCwg4KaV4KeN4Kav4Ka-4Kay4Ka_4Kar4KeL4Kaw4KeN4Kao4Ka_4Kav4Ka84Ka-LCDgpq7gpr7gprDgp43gppXgpr_gpqgg4Kav4KeB4KaV4KeN4Kak4Kaw4Ka-4Ka34KeN4Kaf4KeN4Kaw!5e0!3m2!1sbn!2sbd!4v1532328708137"
        allowfullscreen></iframe> -->
</div>
<!-- ##### Google Maps End ##### -->

<!-- ##### Contact Area Start ##### -->
<section class="contact-area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="contact-content-area">
                    <div class="row">
                        <div class="col-12 col-md-4">
                            <div class="contact-content contact-information">
                                <h4>Contact</h4>
                                <p>info.actschapter2@gmail.com</p>
                                <p>+233 24 448 2798</p>
                            </div>
                        </div>
                        <div class="col-12 col-md-4">
                            <div class="contact-content contact-information">
                                <h4>Address</h4>
                                <p>Achimota</p>
                                <p>Accra, Ghana</p>
                            </div>
                        </div>
                        <div class="col-12 col-md-4">
                            <div class="contact-content contact-information">
                                <h4>Opening Hours</h4>
                                <p>Wednesday: 6pm - 8pm (Bible Studies)</p>
                                <p>Friday: 6am - 10am & 5pm - 8pm (Prayers)</p>
                                <p>Sunday: 7am - 10am</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- ##### Contact Area End ##### -->

<!-- ##### Contact Form Area Start ##### -->
<div class="contact-form section-padding-0-100">
    <div class="container">
        <div class="row">
            <!-- Section Heading -->
            <div class="col-12">
                <div class="section-heading">
                    <h2>Leave A Message</h2>
                    <p>Your email address will not be published. Required fields are marked.</p>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <!-- Contact Form Area -->
                <div class="contact-form-area">
                    <form action="{% url 'mainapp:send_mail' %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group">
                                    <label for="contact-name">Full Name*:</label>
                                    <input name='name' type="text" class="form-control" id="contact-name"
                                        placeholder="Full Name" required>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group">
                                    <label for="contact-email">Email*:</label>
                                    <input name='email' type="email" class="form-control" id="contact-email"
                                        placeholder="info.deercreative@gmail.com" required>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group">
                                    <label for="message">Message*:</label>
                                    <textarea name='message' class="form-control" name="message" id="message" cols="30"
                                        rows="10" placeholder="Message" required></textarea>
                                </div>
                            </div>
                            <div class="col-12 text-center">
                                <button type="submit" class="btn crose-btn mt-15">Submit Now</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ##### Contact Form Area End ##### -->
{% endblock %}